apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-preview
  annotations:
    github.com/project-slug: mariogarcia/backstage-preview
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: mariogarcia
